### ISSUE TITLE
Loading test goes on indefinitely on mac

### ISSUE THREAD

**Issue by nimakam** [Derivitec/vscode-dotnet-adapter#28]
Repro steps:

- Install "Test Explorer UI" and ".NET Core Test Explorer" extensions on VS Code on Mac OS Catalina
- Install lates .NET Core SDK `3.1.301`
- Go to the test explorer and click on reload button
- Go to .NET Core Test Summary and Output windows

Expected:

Tests should load reasonably quickly. Up to 10 seconds for a simple test. Up to 20s for a handful of tests across 4 projects.

Actual:

The following goes on indefinitely. Over 2 minutes. Following is the Test Output window contents with the dots progressively moving forward.

```
[2020-07-10T02:40:36.301Z] Loading tests from 336 files
..................................................................................
```

In the test Summary window the following error keeps repeating, close to once every second.

```
Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Testhost process exited with error: A fatal error was encountered. The library 'libhostpolicy.dylib' required to execute the application was not found in '/Users/nimakamoosi/repos/universal-identity-private/source/shared-test/bin/Debug/netcoreapp3.1/'.
Failed to run as a self-contained app. If this should be a framework-dependent app, add the /Users/nimakamoosi/repos/universal-identity-private/source/shared-test/bin/Debug/netcoreapp3.1/testhost.runtimeconfig.json file specifying the appropriate framework.
. Please check the diagnostic logs for more information.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.ThrowOnTestHostExited(Boolean testHostExited)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler)
Microsoft (R) Test Execution Command Line Tool Version 16.6.0
Copyright (c) Microsoft Corporation.  All rights reserved.
```

When I run the command `dotnet testhost.dll` from each test project output directory using the terminal I get a similar error:

```
macbookair:netcoreapp3.1 nimakamoosi$ dotnet testhost.dll 
A fatal error was encountered. The library 'libhostpolicy.dylib' required to execute the application was not found in '/Users/nimakamoosi/repos/universal-identity-private/source/operator-test/bin/Debug/netcoreapp3.1/'.
Failed to run as a self-contained app. If this should be a framework-dependent app, add the /Users/nimakamoosi/repos/universal-identity-private/source/operator-test/bin/Debug/netcoreapp3.1/testhost.runtimeconfig.json file specifying the appropriate framework.
```

**Comment by andrewbridge** [comment]
Hi there @nimakam,

Sorry for the delay in replying.

What you're seeing is the discovery period failing. The output once every second is a call to `dotnet vstest` which takes some time to call and fail.

However, if you're finding the issue occurs just running `dotnet` in a terminal. The error won't be directly related to the test adapter unfortunately.

Given that you're on .NET Core 3.1, [this StackOverflow thread](https://stackoverflow.com/questions/38085430/the-library-hostpolicy-dll-was-not-found) may be relevant. It looks like some config changes were made since 2.0.

There are also multiple threads that match that error message [[1](https://github.com/dotnet/runtime/issues/30026), [2](https://github.com/RicoSuter/NSwag/issues/838), [3](https://stackoverflow.com/questions/43344089/unable-to-build-publish-os-x-self-contained-net-core-executable)].

If you manage to get the following command to run successfully in a terminal (sample successful output also shown):

```sh
> dotnet vstest testhost.dll -lt
Microsoft (R) Test Execution Command Line Tool Version 0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

The following Tests are available:
    TestMethodNameOne
    TestMethodNameTwo
    TestMethodNameThree
```

and you're still having issues with the test adapter. Feel free to reopen this issue or create a new one, as we'll then have narrowed it down a bit.

Cheers!

**Comment by justinmchase** [comment]
This happens to me to, just installed the plugin it spins forever never loads or runs any tests by default. Spending an hour still can't figure it out.

**Comment by justinmchase** [comment]
OK here is probably the problem:
```
Loaded 930 test files
Added 0 tests to the test suite
    1 new test file
    0 cached test files
    0 test files updated since last cache

[2020-12-04T14:13:03.006Z] Waiting for Omnisharp to complete initialisation. This can take several minutes.
[2020-12-04T14:13:03.013Z] Searching for tests
[2020-12-04T14:13:03.139Z] Loading tests from 930 files
[2020-12-04T14:13:11.545Z] Omnisharp initialisation completed
[2020-12-04T14:14:48.630Z] Searching for tests
[2020-12-04T14:14:48.674Z] Loading tests from 930 files
Still running -> [2020-12-04T14:13:03.139Z] Loading tests from 930 files
......................................................................................................................................................
```

930 files? There should be 1 file, its doing some super aggressive discovery rather than just looking at my projects 😬

**Comment by andrewbridge** [comment]
Hi @justinmchase,

By default, the value for the `searchpatterns` setting is `**/bin/**/*.{dll,exe}` and the value for `skippattern` is `**/{nunit,xunit}.*.dll`.

It's constrained to the workspace you're running the extension in, but otherwise it will attempt to load anything that matches the `searchpatterns` glob pattern(s) and does **not** match the `skippattern` glob pattern.

At Derivitec, we have a convention to suffix all our tests with `Tests` and we build them as dll files, so a simple usage for us would be setting `searchpatterns` to `**/bin/**/*Tests.dll`. We actually also group our tests by type, so we use an object [as described here](https://github.com/Derivitec/vscode-dotnet-adapter/pull/31), but that's an advanced usage.

It looks like you probably want to set `searchpatterns` to `**/bin/Debug/**/*.Test.dll`.

**Comment by andrewbridge** [comment]
Let me know if that gets things going, otherwise I'll re-open this ticket and we can take a deeper look.

This is at least partially our fault on the documentation side, and you're not the only one that's asked for more clarity here.

Furthermore, you've highlighted a point that maybe our default is a bit far reaching! As we've now shipped it as a default for some time, we'll have to consider a migration path, but I think having an onboarding or potentially narrower default search pattern may be a good way forward.

**Comment by justinmchase** [comment]
Its try by constraining the search pattern to be one file specifically it works as expected. I will say this is a pretty confusing out of the box experience, is it not possible to just pick up the files being produced by a given project rather than scanning for testable assemblies?
